// <auto-generated />
using System;
using MWalks.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MWalks.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MWalks.API.Models.Difficulty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Difficulties");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7a1bc1f1-9dcb-42d1-906d-f5bb7921d001"),
                            Name = "Easy"
                        },
                        new
                        {
                            Id = new Guid("fdc29a29-09c9-4897-8c6d-bd62b2f9eab4"),
                            Name = "Moderate"
                        },
                        new
                        {
                            Id = new Guid("9294e56f-6b1d-4784-b64c-ec86ad3a3f98"),
                            Name = "Hard"
                        },
                        new
                        {
                            Id = new Guid("7e22f1d8-3c3a-4e74-bb38-5b350156b9fc"),
                            Name = "Expert"
                        });
                });

            modelBuilder.Entity("MWalks.API.Models.Image", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("SizeInBytes")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("MWalks.API.Models.Region", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("ImageUrl")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Regions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c084a776-99eb-4c2d-9efb-4f964e17f4a3"),
                            Code = "AKL",
                            Name = "Auckland"
                        },
                        new
                        {
                            Id = new Guid("29ff1a54-b7ad-42a0-9e74-fc8cc51bda7b"),
                            Code = "WLG",
                            Name = "Wellington"
                        },
                        new
                        {
                            Id = new Guid("f3d6b858-d0b3-4012-a1d8-50da8cbba12e"),
                            Code = "CHC",
                            Name = "Christchurch"
                        },
                        new
                        {
                            Id = new Guid("3f88b2a8-50c4-46e6-8e4f-9a9b9b4f0ae5"),
                            Code = "HAM",
                            Name = "Hamilton"
                        },
                        new
                        {
                            Id = new Guid("d1c9914b-05c3-4d7a-86ab-1b3c5827cbbc"),
                            Code = "NAP",
                            Name = "Napier"
                        });
                });

            modelBuilder.Entity("MWalks.API.Models.Walk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DifficultyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("ImageUrl")
                        .HasColumnType("varbinary(max)");

                    b.Property<double>("LengthInKm")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RegionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DifficultyId");

                    b.HasIndex("RegionId");

                    b.ToTable("Walks");

                    b.HasData(
                        new
                        {
                            Id = new Guid("56a9b16f-6cfa-4d25-92c7-63d0e3f6d6e4"),
                            Description = "Milford Track is a 53.5 km walk.",
                            DifficultyId = new Guid("9294e56f-6b1d-4784-b64c-ec86ad3a3f98"),
                            LengthInKm = 53.5,
                            Name = "Milford Track",
                            RegionId = new Guid("c084a776-99eb-4c2d-9efb-4f964e17f4a3")
                        },
                        new
                        {
                            Id = new Guid("7eafc632-1ed5-4317-8ff0-5a4d015e5c98"),
                            Description = "The Tongariro Alpine Crossing is a 19.4 km walk.",
                            DifficultyId = new Guid("fdc29a29-09c9-4897-8c6d-bd62b2f9eab4"),
                            LengthInKm = 19.399999999999999,
                            Name = "Tongariro Alpine Crossing",
                            RegionId = new Guid("29ff1a54-b7ad-42a0-9e74-fc8cc51bda7b")
                        },
                        new
                        {
                            Id = new Guid("0a2d547c-7ef0-4bbf-918d-6dfe56b8bc02"),
                            Description = "Kepler Track is a 60 km walk.",
                            DifficultyId = new Guid("9294e56f-6b1d-4784-b64c-ec86ad3a3f98"),
                            LengthInKm = 60.0,
                            Name = "Kepler Track",
                            RegionId = new Guid("f3d6b858-d0b3-4012-a1d8-50da8cbba12e")
                        },
                        new
                        {
                            Id = new Guid("ff0bb60f-f7f1-442b-95e8-e2c9f6d97ad6"),
                            Description = "Routeburn Track is a 32 km walk.",
                            DifficultyId = new Guid("fdc29a29-09c9-4897-8c6d-bd62b2f9eab4"),
                            LengthInKm = 32.0,
                            Name = "Routeburn Track",
                            RegionId = new Guid("3f88b2a8-50c4-46e6-8e4f-9a9b9b4f0ae5")
                        },
                        new
                        {
                            Id = new Guid("82a9b1f6-4e7e-4d85-9f8d-763e3e8b08f5"),
                            Description = "Abel Tasman Coast Track is a 60 km walk.",
                            DifficultyId = new Guid("7a1bc1f1-9dcb-42d1-906d-f5bb7921d001"),
                            LengthInKm = 60.0,
                            Name = "Abel Tasman Coast Track",
                            RegionId = new Guid("d1c9914b-05c3-4d7a-86ab-1b3c5827cbbc")
                        });
                });

            modelBuilder.Entity("MWalks.API.Models.Walk", b =>
                {
                    b.HasOne("MWalks.API.Models.Difficulty", "Difficulty")
                        .WithMany()
                        .HasForeignKey("DifficultyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MWalks.API.Models.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Difficulty");

                    b.Navigation("Region");
                });
#pragma warning restore 612, 618
        }
    }
}
